version: "3.8"

services:
  # app:
  #   image: inteliver-api:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-inteliver}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inteliver_network
    ports:
      - "127.0.0.1:5432:5432"

networks:
  inteliver_network:
    name: "inteliver-network"
    driver: bridge

volumes:
  postgres_data: