version: "3.8"

# This docker compose runs postgres and minio service only for development.
# Use `make dev` command for running intliver in dev mode.

services:
  postgres:
    image: postgres:16
    container_name: postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-inteliver}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - inteliver

    ports:
      - "127.0.0.1:5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-07-26T20-48-21Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    volumes:
      - inteliver_minio_data:/data
    networks:
      - inteliver
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  inteliver:
    name: "inteliver"
    driver: bridge

volumes:
  postgres_data:
  inteliver_minio_data:
