name: Publish to PyPI

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            requirements.txt

      # Step 3: Install build dependencies
      - name: Install build dependencies
        run: pip install --upgrade pip setuptools wheel build twine

      # Step 4: Build the package
      - name: Build the package
        run: python -m build

      # Step 5: Lint the distribution files
      # Optional but recommended: This step ensures the distribution files are well-formed.
      - name: Check the distribution files with twine
        run: twine check dist/*

      # Step 6: Publish the package to PyPI
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      # Step 7: Post-publish checks (optional)
      # Optional: Verify that the package was successfully published
      - name: Verify published package
        run: pip install inteliver --index-url https://pypi.org/simple --no-cache-dir --disable-pip-version-check
