name: Run tests and Publish to CodeClimate

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    paths:
      - '!*.MD'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inteliver
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Set up database with Alembic
      run: |
        alembic upgrade head

    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}/src  # Set PYTHONPATH to the src directory
      run: |
        pytest --disable-warnings --cov=inteliver --cov-report=xml --cov-report=html tests/

    - name: Upload coverage to Code Climate
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    #   with:
    #     coverageCommand: pytest --disable-warnings --cov=inteliver --cov-report=xml tests/
    #     coverageLocations: ./coverage.xml
    #     debug: true