name: Publish Tests to CodeClimate

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:
    paths:
      - '!*.MD'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: inteliver
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
      minio:
        image: minio/minio:RELEASE.2024-07-26T20-48-21Z
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
          - 9001:9001
        options: >-
          --health-cmd="curl -f http://localhost:9000/minio/health/live || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
          --entrypoint sh
        command: -c "mkdir -p /data && minio server /data --console-address ':9001'"

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready"
            break
          fi
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Wait for MinIO to be ready
      run: |
        for i in {1..30}; do
          if curl -f http://localhost:9000/minio/health/live; then
            echo "MinIO is ready"
            break
          fi
          echo "Waiting for MinIO..."
          sleep 2
        done

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Set up database with Alembic
      run: |
        alembic upgrade head

    - name: Build i18n translation .mo files
      run: |
        pybabel compile -d src/inteliver/translations

    - name: Run tests with coverage
      env:
        PYTHONPATH: ${{ github.workspace }}/src  # Set PYTHONPATH to the src directory
      run: |
        pytest --disable-warnings --cov=inteliver --cov-report=xml --cov-report=html tests/

    - name: Upload coverage to Code Climate
      uses: paambaati/codeclimate-action@v9.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

    #   with:
    #     coverageCommand: pytest --disable-warnings --cov=inteliver --cov-report=xml tests/
    #     coverageLocations: ./coverage.xml
    #     debug: true